###
@base_url = http://localhost:8001/api/v1
###
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDEvYXBpL3YxL2F1dGgvbG9naW4iLCJpYXQiOjE3Njk1ODI0MDgsImV4cCI6MTc2OTU4NjAwOCwibmJmIjoxNzY5NTgyNDA4LCJqdGkiOiJjdlhnc291ZUVzcUNyZVNFIiwic3ViIjoiYTBkZjE5M2ItYmQ4Ny00OWZjLWE1NjEtMGNhODMzNjgxNTVkIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsInN0YXR1cyI6ImFrdGlmIn0.nvdR22qqn83j5b6Hkq-axG2ANGBDUDfN9_kxeqF0gyE
### Login
POST {{ base_url }}/auth/login
Content-Type: application/json

{
  "username": "dosen.pa@example.com",
  "password": "password"
}

### Logout
POST {{ base_url }}/auth/logout
Authorization: Bearer {{ token }}

### Refresh token
POST {{ base_url }}/auth/refresh
Authorization: Bearer {{ token }}

### Get user profile
GET {{ base_url }}/auth/me
Authorization: Bearer {{ token }}

### Get list of Users
GET {{ base_url }}/users
Authorization: Bearer {{ token }}

### Get list of Administrators
GET {{ base_url }}/dashboard/admin
Authorization: Bearer {{ token }}
### Get list of BAAK
GET {{ base_url }}/dashboard/baak
Authorization: Bearer {{ token }}
### Get list of Dosen PA
GET {{ base_url }}/dashboard/dosen-pa
Authorization: Bearer {{ token }}
### Get list of Dosen Pengampu
GET {{ base_url }}/dashboard/dosen-pengampu
Authorization: Bearer {{ token }}
### Get list of Mahasiswa
GET {{ base_url }}/dashboard/mahasiswa
Authorization: Bearer {{ token }}

### Get list of Permissions Menu
GET http://localhost:8001/api/permissions/menu
Authorization: Bearer {{ token }}

### Get list of Users
GET {{ base_url }}/mahasiswa
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/dosen
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/beban-ajar-dosen
Authorization: Bearer {{ token }}
### Get list of dosen mk
GET http://localhost:8001/api/dosenmatakuliah
Authorization: Bearer {{ token }}
### Get list of dosen mk
GET http://localhost:8001/api/dosenpa
Authorization: Bearer {{ token }}
### Get list of dosen mk
GET http://localhost:8001/api/dosenpa/a07e32be-dca6-484c-9dc5-db97c9db4385
Authorization: Bearer {{ token }}
### Get list of dosen mk
GET http://localhost:8001/api/dosenpengampu/a07e7d0b-fb28-4152-aa5e-6f70abb6638b
Authorization: Bearer {{ token }}
### Get list of dosen mk
GET http://localhost:8001/api/dosenpengampu
Authorization: Bearer {{ token }}


### Get list of dosen mk
GET http://localhost:8001/api/akademik/kalender
Authorization: Bearer {{ token }}
### Get list of dosen mk
GET http://localhost:8001/api/akademik/kalender/c3071651-d1fd-4c0a-9117-d95ddbc0f784
Authorization: Bearer {{ token }}


### Get list of Users
GET {{ base_url }}/mata-kuliah
Authorization: Bearer {{ token }}

### Get list of Users
GET {{ base_url }}/mata-kuliah/semester/3?id_kurikulum=a0c773d9-f8b6-40e4-b9e0-61bdc7a4eda9
Authorization: Bearer {{ token }}

### Store Mata Kuliah dengan Token
POST {{ base_url }}/mata-kuliah
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id_prodi": "55874407-7512-4312-a94d-f3049e3cdb68",
    "id_kurikulum": "b5f0b0e4-4fc6-425e-b1f1-1f0d190a3fa9",
    "semester_rekomendasi": 3,
    "mata_kuliah": [
        {
            "kode_mk": "MK001",
            "nama_mk": "Matematika Dasar",
            "teori": 2,
            "praktikum": 1,
            "klinik": 0
        }
    ]
}
### Update Mata Kuliah Semester dengan Token
PUT {{ base_url }}/mata-kuliah/semester/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "id_prodi": "55874407-7512-4312-a94d-f3049e3cdb68",
  "id_kurikulum": "b5f0b0e4-4fc6-425e-b1f1-1f0d190a3fa9",
  "semester_rekomendasi": 3,
  "mata_kuliah": [
    {
      "id": "a0c57af7-9d64-4a84-bf7f-214eb0e41783",
      "kode_mk": "MK001",
      "nama_mk": "Matematika Diskrit",
      "teori": 2,
      "praktikum": 1,
      "klinik": 0
    },
    {
      "id": "a0c584a4-15f8-4023-b5b9-2c571f71fdc9",
      "kode_mk": "MK002",
      "nama_mk": "Pemrograman Web",
      "teori": 3,
      "praktikum": 2,
      "klinik": 0
    }
  ]
}

### Get list of Users
GET {{ base_url }}/kelas-mk/a0e6f4e3-239b-4a30-989a-f7df52c462ac/edit
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/kelas-mk/create
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/kelas-mk/create?nama_prodi=Sarjana+Keperawatan&semester=1
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/kelas-mk
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/kelas-mk/a0f02df3-c85b-4cdd-9f2d-707140f7baf0/edit
Authorization: Bearer {{ token }}

### Get list of Users
GET {{ base_url }}/dosen-mk
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/dosen-mk/create
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/dosen-mk-jadwal/a0e4eb99-fc5d-43da-b1ff-4a6778ed5570/create
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/jadwal-beban-ajar-dosen/a0ec460a-3903-4a16-a2d0-6fcfeb584d61
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/krs
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/pengajuan-krs/daftar-matkul
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/pengajuan-krs/status
Authorization: Bearer {{ token }}
### Get list of Users
DELETE {{ base_url }}/pengajuan-krs/a0f18d67-a046-4dd8-bae4-0f99a05b0dbc
Authorization: Bearer {{ token }}
### Get list of Users
GET {{ base_url }}/dosen/verifikasi-krs/daftar-verifikasi
Authorization: Bearer {{ token }}

### Get Prodi
GET {{ base_url }}/landing/prodi
### Get Mahasiswa Baru
GET {{ base_url }}/mahasiswa-baru
Authorization: Bearer {{ token }}

### Sync Mahasiswa Baru by Periode
POST {{ base_url }}/mahasiswa-baru/sync
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "id_periode_pendaftaran": "a0d0a8b7-2b9c-498f-a151-fa749da273e1"
}
